name: Update Calendar

on:
  schedule:
    - cron: '0 20 * * *' # 每天自動跑一次
  workflow_dispatch: # 允許手動按按鈕跑

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 給機器人寫入權限
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests lunarcalendar

      - name: Run script
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add calendar.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update calendar" && git push)
